---
name: "Mediathek Downloader"
guid: "a31b415a-5264-419d-b152-8c8192a54994"
version: "0.6.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Sucht und lädt Inhalte aus den Mediatheken über die MediathekViewWeb-API."
description: >
  Mit dem Plugin kann man die Mediatheken der öffentlich-rechtlichen Sender in Deutschland durchsuchen und Inhalte herunterladen.
  Für die suche wird die MediathekViewWeb-API verwendet. Der Videos werden direkt über die Original-URLs der Sender heruntergeladen.
  Es können Abos anglegt werden um z.B. Serien automatisch herunterzuladen.
category: "General"
owner: "CatNoir2006"
artifacts:
- "Jellyfin.Plugin.MediathekViewDL.dll"
changelog: >
  changelog
