services:
  plugin_build:
    build:
      context: .
      dockerfile: Tools/TestBuild/Dockerfile.Testbuild
    volumes:
      - ./jellyfin-config:/config

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin_debug
    depends_on:
      plugin_build:
        condition: service_completed_successfully
    ports:
      - "8096:8096"
    volumes:
      # Jellyfin Konfiguration
      - ./jellyfin-config:/config

      # SMB-Share via fstab mount (Host: /mnt/JellyfinMedia)
      - /mnt/JellyfinMedia:/media/smb:ro

    environment:
      - DOTNET_DEBUGGER_CHROME=1
      - COMPlus_EnableDiagnostics=1
      - ASPNETCORE_ENVIRONMENT=Development
